# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bargain-pro"
client_id = "b5a9576542a99d4a9155a9b9f85b4cb9"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "usamaasghar.myshopify.com"
