# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "bargain-pro-app"
client_id = "625995763bdcf76cce2f7b8300fac33c"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-7551b5da.myshopify.com"
